const fs = require("fs");
const path = require("path");

const structure = [
  ".env",
  "config.js",
  "package.json",
  "package-lock.json",
  "index.js",
  "deploy-commands.js",
  "test_db.js",
  "README.md",

  "commands/admin/moderation/ban.js",
  "commands/admin/moderation/unban.js",
  "commands/admin/moderation/softban.js",
  "commands/admin/moderation/kick.js",
  "commands/admin/moderation/blacklist.js",
  "commands/admin/moderation/timeout.js",
  "commands/admin/moderation/untimeout.js",
  "commands/admin/moderation/warn.js",
  "commands/admin/moderation/warnings.js",
  "commands/admin/moderation/clearwarn.js",
  "commands/admin/moderation/removewarn.js",
  "commands/admin/moderation/addrole.js",
  "commands/admin/moderation/removerole.js",
  "commands/admin/moderation/roleall.js",
  "commands/admin/moderation/purge.js",
  "commands/admin/moderation/lock.js",
  "commands/admin/moderation/unlock.js",
  "commands/admin/moderation/slowmode.js",
  "commands/admin/moderation/setnick.js",
  "commands/admin/moderation/vmute.js",
  "commands/admin/moderation/vunmute.js",
  "commands/admin/moderation/nuke.js",

  "commands/admin/setup/setprefix.js",
  "commands/admin/setup/setupConfess.js",
  "commands/admin/setup/setupTicket.js",
  "commands/admin/setup/setupRoles.js",
  "commands/admin/setup/setupLogs.js",
  "commands/admin/setup/setupVoice.js",
  "commands/admin/setup/setupAnime.js",
  "commands/admin/setup/setupWelcome.js",
  "commands/admin/setup/setupGoodbye.js",
  "commands/admin/setup/setupBoost.js",

  "commands/security/antinuke.js",
  "commands/security/antiraid.js",
  "commands/security/automod.js",
  "commands/security/antilink.js",
  "commands/security/verify.js",
  "commands/security/altidentifier.js",
  "commands/security/antighostping.js",

  "commands/mabar/ajak.js",
  "commands/mabar/party.js",
  "commands/mabar/bubar.js",
  "commands/mabar/setprofile.js",
  "commands/mabar/profile.js",
  "commands/mabar/stats.js",
  "commands/mabar/schedule.js",

  "commands/rpg/core/profile.js",
  "commands/rpg/core/stats.js",
  "commands/rpg/core/rank.js",
  "commands/rpg/core/leaderboard.js",
  "commands/rpg/core/classes.js",

  "commands/rpg/economy/bank.js",
  "commands/rpg/economy/transfer.js",
  "commands/rpg/economy/rob.js",
  "commands/rpg/economy/shop.js",
  "commands/rpg/economy/sell.js",
  "commands/rpg/economy/gacha.js",
  "commands/rpg/economy/housing.js",

  "commands/rpg/actions/daily.js",
  "commands/rpg/actions/weekly.js",
  "commands/rpg/actions/explore.js",
  "commands/rpg/actions/dungeon.js",
  "commands/rpg/actions/bossfight.js",
  "commands/rpg/actions/hunt.js",
  "commands/rpg/actions/fish.js",
  "commands/rpg/actions/mine.js",
  "commands/rpg/actions/chop.js",
  "commands/rpg/actions/farm.js",
  "commands/rpg/actions/train.js",
  "commands/rpg/actions/bounty.js",

  "commands/rpg/progression/inventory.js",
  "commands/rpg/progression/use.js",
  "commands/rpg/progression/equip.js",
  "commands/rpg/progression/unequip.js",
  "commands/rpg/progression/blacksmith.js",
  "commands/rpg/progression/cook.js",
  "commands/rpg/progression/alchemy.js",
  "commands/rpg/progression/timetravel.js",
  "commands/rpg/progression/skills.js",
  "commands/rpg/progression/pets.js",
  "commands/rpg/progression/guild.js",

  "commands/tickets/close.js",
  "commands/tickets/add.js",
  "commands/tickets/remove.js",
  "commands/tickets/transcript.js",

  "commands/confess/reply.js",
  "commands/confess/block.js",

  "commands/giveaways/gstart.js",
  "commands/giveaways/gend.js",
  "commands/giveaways/greroll.js",
  "commands/giveaways/glist.js",
  "commands/giveaways/gedit.js",
  "commands/giveaways/gdrop.js",

  "commands/ai/chat.js",
  "commands/ai/imagine.js",
  "commands/ai/summarize.js",
  "commands/ai/translate.js",
  "commands/ai/vision.js",
  "commands/ai/persona.js",

  "commands/anime/waifu.js",
  "commands/anime/husbando.js",
  "commands/anime/cosplay.js",
  "commands/anime/anime.js",
  "commands/anime/manga.js",
  "commands/anime/character.js",
  "commands/anime/animenews.js",
  "commands/anime/quote.js",
  "commands/anime/recommend.js",
  "commands/anime/animesearch.js",

  "commands/music/play.js",
  "commands/music/skip.js",
  "commands/music/stop.js",
  "commands/music/queue.js",
  "commands/music/clearqueue.js",
  "commands/music/pause.js",
  "commands/music/resume.js",
  "commands/music/volume.js",
  "commands/music/loop.js",
  "commands/music/shuffle.js",
  "commands/music/playlist.js",
  "commands/music/lyrics.js",
  "commands/music/filters.js",
  "commands/music/autoplay.js",

  "commands/voice/vclimit.js",
  "commands/voice/vckick.js",
  "commands/voice/vcname.js",
  "commands/voice/vcprivate.js",
  "commands/voice/vclock.js",
  "commands/voice/vcclaim.js",
  "commands/voice/vcghost.js",

  "commands/image/blurpify.js",
  "commands/image/wasted.js",
  "commands/image/triggered.js",
  "commands/image/petpet.js",
  "commands/image/meme.js",
  "commands/image/welcomecard.js",
  "commands/image/goodbyecard.js",
  "commands/image/boostcard.js",

  "commands/games/uno.js",
  "commands/games/chess.js",
  "commands/games/werewolf.js",
  "commands/games/wordle.js",
  "commands/games/hangman.js",
  "commands/games/connect4.js",
  "commands/games/minesweeper.js",

  "commands/fun/ship.js",
  "commands/fun/trivia.js",
  "commands/fun/rps.js",
  "commands/fun/tictactoe.js",
  "commands/fun/snake.js",
  "commands/fun/interact.js",
  "commands/fun/hug.js",
  "commands/fun/kiss.js",
  "commands/fun/slap.js",
  "commands/fun/pat.js",
  "commands/fun/8ball.js",
  "commands/fun/joke.js",
  "commands/fun/truth.js",
  "commands/fun/dare.js",

  "commands/information/weather.js",
  "commands/information/crypto.js",
  "commands/information/covid.js",
  "commands/information/movie.js",
  "commands/information/github.js",

  "commands/utility/ping.js",
  "commands/utility/help.js",
  "commands/utility/info.js",
  "commands/utility/math.js",
  "commands/utility/avatar.js",
  "commands/utility/userinfo.js",
  "commands/utility/serverinfo.js",
  "commands/utility/remindme.js",
  "commands/utility/afk.js",
  "commands/utility/poll.js",
  "commands/utility/suggest.js",
  "commands/utility/report.js",
  "commands/utility/autoresponder.js",
  "commands/utility/rep.js",

  "models/guildSchema.js",
  "models/userSchema.js",
  "models/gameProfileSchema.js",
  "models/mabarSessionSchema.js",
  "models/confessBanSchema.js",
  "models/rpgSchema.js",
  "models/inventorySchema.js",
  "models/petSchema.js",
  "models/ticketSchema.js",
  "models/warnSchema.js",
  "models/giveawaySchema.js",
  "models/animeTrackerSchema.js",

  "helpers/logger.js",
  "helpers/utils.js",
  "helpers/embed.js",
  "helpers/musicHandler.js",
  "helpers/rpgSystem.js",
  "helpers/canvasHelper.js",
  "helpers/aiHelper.js",
  "helpers/voiceHelper.js",
  "helpers/securityHelper.js",
  "helpers/animeTracker.js",

  "cronjobs/dailyReset.js",
  "cronjobs/giveawayCheck.js",
  "cronjobs/mabarTimeout.js",
  "cronjobs/animeDailySchedule.js",
  "cronjobs/animeAiringNotify.js",

  "data/items.json",
  "data/recipes.json",
  "data/shop.json",
  "data/monsters.json",
  "data/quests.json",
  "data/pets.json",
  "data/animeQuotes.json",
  "data/gamesList.json",

  "events/discord/ready.js",
  "events/discord/messageCreate.js",
  "events/discord/interactionCreate.js",
  "events/discord/guildMemberAdd.js",
  "events/discord/guildMemberRemove.js",
  "events/discord/guildMemberUpdate.js",
  "events/discord/voiceStateUpdate.js",
  "events/discord/messageDelete.js",
  "events/discord/messageUpdate.js",
  "events/discord/channelDelete.js",
  "events/discord/roleDelete.js",

  "events/distube/playSong.js",
  "events/distube/addSong.js",
  "events/distube/finish.js",
  "events/distube/error.js",
  "events/distube/empty.js",

  "handlers/commandHandler.js",
  "handlers/slashCommandHandler.js",
  "handlers/eventHandler.js",
  "handlers/cronHandler.js",

  "logs/error.log",
  "logs/system.log"
];

structure.forEach(file => {
  const dir = path.dirname(file);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  if (!fs.existsSync(file)) {
    fs.writeFileSync(file, "", "utf8");
    console.log("✔", file);
  }
});

console.log("\nSemua folder dan file berhasil dibuat.");